Repository simplic/simplic-service, pull requests merged in 2018-06, with the labels that each got.

#13 Add lambda-style-get-method in cache services and cleanup interfaces
  simplic-cache/Simplic.Cache.Service/CacheService.cs
  simplic-cache/Simplic.Cache.Service/Properties/AssemblyInfo.cs
  simplic-cache/Simplic.Cache.Service/WeakReferenceCacheService.cs
  simplic-cache/Simplic.Cache.Test/CacheTest.cs
  simplic-cache/Simplic.Cache/Interface/ICacheService.cs
  simplic-cache/Simplic.Cache/Interface/IWeakReferenceCacheService.cs
  simplic-cache/Simplic.Cache/Properties/AssemblyInfo.cs
Labels: enhancement

#19 Change migration script
  simplic-authorization/Simplic.Authorization.Service/AuthorizationService.cs
  simplic-authorization/Simplic.Authorization.Service/Properties/AssemblyInfo.cs
Labels: bug, enhancement

#18 Fix sum bug if sequence is empty
  simplic-corelib/Simplic.CoreLib/Data/PreciseDecimal.cs
  simplic-corelib/Simplic.CoreLib/Properties/AssemblyInfo.cs
Labels: bug

#17 Add autologin
  simplic-authentication/Simplic.Authentication.Service/AuthenticationService.cs
  simplic-authentication/Simplic.Authentication.Service/AutologinModel.cs
  simplic-authentication/Simplic.Authentication.Service/Properties/AssemblyInfo.cs
  simplic-authentication/Simplic.Authentication.Service/Simplic.Authentication.Service.csproj
  simplic-authentication/Simplic.Authentication.Service/packages.config
  simplic-authentication/Simplic.Authentication/Interface/IAuthenticationService.cs
  simplic-authentication/Simplic.Authentication/Properties/AssemblyInfo.cs
Labels: enhancement

#23 parse error
  simplic-sql/Simplic.Sql/Properties/AssemblyInfo.cs
  simplic-sql/Simplic.Sql/TypeHandler/PreciseDecimalHandler.cs
Labels: bug

#26 get api user method
  .github/PULL_REQUEST_TEMPLATE.md
  simplic-authentication/Simplic.Authentication.Service/AuthenticationService.cs
  simplic-authentication/Simplic.Authentication.Service/Properties/AssemblyInfo.cs
  simplic-authentication/Simplic.Authentication.Service/Simplic.Authentication.Service.csproj
  simplic-authentication/Simplic.Authentication.Service/packages.config
  simplic-authentication/Simplic.Authentication/Interface/IAuthenticationService.cs
  simplic-authentication/Simplic.Authentication/Properties/AssemblyInfo.cs
  simplic-user/Simplic.User.Service/Properties/AssemblyInfo.cs
  simplic-user/Simplic.User.Service/Simplic.User.Service.csproj
  simplic-user/Simplic.User.Service/UserService.cs
  simplic-user/Simplic.User.Service/packages.config
  simplic-user/Simplic.User/Interface/IUserService.cs
  simplic-user/Simplic.User/Properties/AssemblyInfo.cs
Labels: enhancement
